# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftDev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftDev
  pod 'RxSwiftExt', '~> 5'
  target 'RxSwiftDevTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
